# Generated by Django 4.0.2 on 2022-04-11 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavina_auth', '0003_place_relief_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='heighest_elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='heighest_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
