# Generated by Django 4.0.2 on 2022-04-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lavina_auth', '0004_place_heighest_elevation_place_heighest_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='relief_map',
        ),
    ]
